from uuid import uuid4

from asgi_correlation_id import CorrelationIdMiddleware

CORRELATION_ID_WHITELIST_CHARS = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789")
HTTP_REQUEST_ID_HEADER = "Request-Id"  # NB: do not change this without also changing tp_request_id in the routes!


class InjectCloudflareRayId:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            return

        headers = dict(scope["headers"])
        request_id_header = HTTP_REQUEST_ID_HEADER.lower().encode("utf8")

        # Remove any sneaky upstream Request-Id that could arrive from untrusted external
        if headers.get(request_id_header):
            del headers[request_id_header]

        cf_ray = headers.get(b"cf-ray")
        if cf_ray:
            headers[request_id_header] = cf_ray

        scope["headers"] = [(k, v) for k, v in headers.items()]
        await self.app(scope, receive, send)


def asgi_correlation_id_validator(value: str):
    """
    Carefully validate the correlation_id to prevent it becoming an injection vector

    Must be in the format:-
     - 9e891276c7774393-TPX   <<< the TPX suffix means the correlation_id was internally generated by threatpatrols-api
     - 798bc1d16995a889-SYD   <<< standard format Cloudflare CF-Ray

    :param value:
    :return:
    """

    value_parts = str(value).split("-")

    if len(value_parts) != 2:
        return False

    if len(value_parts[1]) != 3 or any(char not in CORRELATION_ID_WHITELIST_CHARS for char in value_parts[1]):
        return False

    if len(value_parts[0]) != 16 or any(char not in CORRELATION_ID_WHITELIST_CHARS for char in value_parts[0]):
        return False

    return True


def add_asgi_correlation_middleware(app):
    """
    Establishes a Request-Id per HTTP Request

    The CorrelationIdMiddleware module is designed to >not< create a new Correlation-Id if it already exists
    If the request has a (Cloudflare) CF-Ray header we use it - this paradigm could be used with others if needed
    :param app:
    :return:
    """

    app.add_middleware(
        CorrelationIdMiddleware,
        header_name=HTTP_REQUEST_ID_HEADER,
        generator=lambda: f"{uuid4().hex[0:16]}-TPX",  # NB: not applied if InjectCloudflareRayId already injected
        validator=asgi_correlation_id_validator,
    )

    # NB: this appears in code _after_ CorrelationIdMiddleware but at run-time occurs _before_ CorrelationIdMiddleware
    app.add_middleware(InjectCloudflareRayId)
